### ISSUE TITLE
T8suite crashes in Wine when files are present in the "TuningPacks" dir

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/TuningSuites#19]
T8suite checks for files in the TuningPacks dir at startup but something in the check makes T8suite crash. This is ONLY an issue when running in Wine/Crossover, currently in OsX.

Found some more info on google, time to check missing files and build setup I guess :)
https://stackoverflow.com/questions/6244939/how-do-i-fix-a-net-windows-application-crashing-at-startup-with-exception-code

From the error console in Wine:
Unhandled exception: 0xe0434352 in 32-bit code (0x7b82b36f).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:1007 GS:000f
 EIP:7b82b36f ESP:0033f064 EBP:0033f0d0 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:7b8188c9 EBX:00000005 ECX:00000000 EDX:00000000
 ESI:0033f12c EDI:00168460
Stack dump:
0x0033f064:  0033f12c 00000014 003725b4 0033f080
0x0033f074:  79157a53 e0434352 00000001 00000000
0x0033f084:  7b82b36f 00000005 80004005 00000000
0x0033f094:  00000000 00000000 79140000 79150579
0x0033f0a4:  0033f0b4 02000059 0033f0b8 7915bc5e
0x0033f0b4:  003ec828 0033f0c8 791ca99c 06192a1c
0200: sel=1007 base=7ffc0000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x7b82b36f RaiseException+0x7f() in kernel32 (0x0033f0d0)
  1 0x791cac08 in clr (+0x8ac07) (0x0033f160)
  2 0x791cae41 in clr (+0x8ae40) (0x0033f220)
  3 0x1074ee9c (0x0033f23c)
  4 0x1074e177 (0x0033f27c)
  5 0x1074800b (0x0033f2e4)
  6 0x06234c7d (0x0033f314)
  7 0x03b726a0 (0x0033f324)
  8 0x791421db in clr (+0x21da) (0x0033f334)
  9 0x79164a2a in clr (+0x24a29) (0x0033f3b0)
  10 0x79164bcc in clr (+0x24bcb) (0x0033f4f0)
  11 0x79164c01 in clr (+0x24c00) (0x0033f50c)
  12 0x79164c21 in clr (+0x24c20) (0x0033f524)
  13 0x7922ce82 in clr (+0xece81) (0x0033f688)
  14 0x7922cf90 in clr (+0xecf8f) (0x0033f8f0)
  15 0x7922cda4 in clr (+0xecda3) (0x0033fdd4)
  16 0x7922d199 in clr (+0xed198) (0x0033fe28)
  17 0x7922d09a in clr (+0xed099) (0x0033fe74)
  18 0x792aaf00 in clr (+0x16aeff) (0x0033feac)
  19 0x603b55ab in mscoreei (+0x55aa) (0x0033feb8)
  20 0x79007f16 in mscoree (+0x7f15) (0x0033fec8)
  21 0x79004de3 in mscoree (+0x4de2) (0x0033fee8)
  22 0x7b852258 CloseHandle+0x157() in kernel32 (0x0033ff28)
  23 0x7bc6b32c call_thread_func_wrapper+0xb() in ntdll (0x0033ff38)
  24 0x7bc6d41d call_thread_func+0x6c() in ntdll (0x0033ffb8)
  25 0x7bc6b2f2 call_thread_entry_point+0x11() in ntdll (0x0033ffd8)
  26 0x7bc45b3f in ntdll (+0x35b3e) (0x0033ffe8)
0x7b82b36f RaiseException+0x7f in kernel32: movl	%ebp,%esp
Modules:
Module	Address			Debug info	Name (280 modules)
PE	  400000-  876000	Deferred        t8suitepro
PE	48800000-48d35000	Deferred        appleintelhd3000graphicsgldriver
PE	48d35000-48e10000	Deferred        amdradeonx3000gldriver
PE	48e10000-4908d000	Deferred        atiradeonx3000sclib.dylib
ELF	49751000-497bc000	Deferred        advapi32<elf>
  \-PE	49760000-497b3000	\               advapi32
ELF	497bc000-497d5000	Deferred        version<elf>
  \-PE	497c0000-497d4000	\               version
ELF	497d5000-497f7000	Deferred        imm32<elf>
  \-PE	497e0000-497f5000	\               imm32
PE	4b8d5000-4ba89000	Stabs           libwine.1.dylib
ELF	4ba89000-4baf7000	Deferred        shlwapi<elf>
  \-PE	4ba90000-4baef000	\               shlwapi
ELF	4baf7000-4bc35000	Deferred        user32<elf>
  \-PE	4bb00000-4bc0a000	\               user32
ELF	4bc35000-4bd40000	Deferred        gdi32<elf>
  \-PE	4bc40000-4bce8000	\               gdi32
ELF	4bd40000-4bdbe000	Deferred        libcxfreetype.so
ELF	4bdbe000-4bece000	Deferred        ole32<elf>
  \-PE	4bdc0000-4bebe000	\               ole32
ELF	4bece000-4bf44000	Deferred        rpcrt4<elf>
  \-PE	4bed0000-4bf3e000	\               rpcrt4
ELF	4bf44000-4bfd3000	Deferred        winemac<elf>
  \-PE	4bf50000-4bfc6000	\               winemac
ELF	4c09c000-4c0de000	Deferred        rsaenh<elf>
  \-PE	4c0a0000-4c0dc000	\               rsaenh
ELF	4c0de000-4c1a5000	Deferred        crypt32<elf>
  \-PE	4c0e0000-4c19d000	\               crypt32
ELF	4c1a5000-4c1d9000	Deferred        uxtheme<elf>
  \-PE	4c1b0000-4c1d7000	\               uxtheme
ELF	4c1d9000-4c21b000	Deferred        ws2_32<elf>
  \-PE	4c1e0000-4c218000	\               ws2_32
ELF	4c21b000-4c2a7000	Deferred        urlmon<elf>
  \-PE	4c220000-4c2a2000	\               urlmon
ELF	4c2a7000-4c3ba000	Deferred        oleaut32<elf>
  \-PE	4c2b0000-4c38f000	\               oleaut32
ELF	4c3ba000-4c5d9000	Deferred        shell32<elf>
  \-PE	4c3c0000-4c5d2000	\               shell32
ELF	4c5d9000-4c64c000	Deferred        wininet<elf>
  \-PE	4c5e0000-4c648000	\               wininet
ELF	4c64c000-4c671000	Deferred        mpr<elf>
  \-PE	4c650000-4c66f000	\               mpr
ELF	4c671000-4c685000	Deferred        shfolder<elf>
  \-PE	4c680000-4c684000	\               shfolder
ELF	4c685000-4c77d000	Deferred        comctl32<elf>
  \-PE	4c690000-4c779000	\               comctl32
ELF	4c77d000-4c802000	Deferred        gdiplus<elf>
  \-PE	4c780000-4c7f9000	\               gdiplus
ELF	4fc5a000-4fcf5000	Deferred        windowscodecs<elf>
  \-PE	4fc60000-4fcec000	\               windowscodecs
PE	4fcf5000-4fd25000	Deferred        libcxpng16.dylib
PE	4fd25000-4fd5e000	Deferred        libcxjpeg.dylib
PE	5e0d0000-5e17a000	Deferred        diasymreader
PE	60340000-6034d000	Deferred        culture
PE	603b0000-60416000	Export          mscoreei
PE	60930000-60940000	Deferred        nlssorting
PE	61470000-6174c000	Deferred        system.data
PE	79000000-7904a000	Export          mscoree
PE	79060000-7911e000	Deferred        msvcr100_clr0400
PE	79140000-797af000	Export          clr
PE	79810000-79870000	Deferred        clrjit
ELF	7b800000-7ba52000	Stabs           kernel32<elf>
  \-PE	7b810000-7ba42000	\               kernel32
ELF	7bc00000-7bcd5000	Stabs           ntdll<elf>
  \-PE	7bc10000-7bcb3000	\               ntdll
ELF	7bf00000-7bf15000	Deferred        <wine-loader>
PE	91758000-91759000	Deferred        accelerate
PE	91759000-91771000	Deferred        libcginterfaces.dylib
PE	91771000-91dd8000	Deferred        vimage
PE	91dd8000-91f25000	Deferred        libblas.dylib
PE	91f25000-91f38000	Deferred        libbnns.dylib
PE	91f38000-922d4000	Deferred        liblapack.dylib
PE	922d4000-922eb000	Deferred        liblinearalgebra.dylib
PE	922eb000-92306000	Deferred        libsparseblas.dylib
PE	92306000-92454000	Deferred        libvdsp.dylib
PE	92454000-92536000	Deferred        libvmisc.dylib
PE	92536000-92537000	Deferred        veclib
PE	92537000-93295000	Deferred        appkit
PE	93295000-93296000	Deferred        applicationservices
PE	93296000-93305000	Deferred        ats
PE	9339d000-934cb000	Deferred        libfontparser.dylib
PE	934cb000-93518000	Deferred        libfontregistry.dylib
PE	93518000-9354c000	Deferred        libtruetypescaler.dylib
PE	935b8000-93669000	Deferred        colorsync
PE	93669000-936c0000	Deferred        hiservices
PE	936c0000-936d0000	Deferred        langanalysis
PE	936d0000-93729000	Deferred        printcore
PE	93729000-937c4000	Deferred        qd
PE	937c4000-937d1000	Deferred        speechsynthesis
PE	937d1000-939c3000	Deferred        audiotoolbox
PE	939c3000-939c4000	Deferred        audiounit
PE	939c4000-93d78000	Deferred        cfnetwork
PE	93d78000-93d79000	Deferred        carbon
PE	93d79000-93d83000	Deferred        carbonsound
PE	93d83000-93d88000	Deferred        commonpanels
PE	93d88000-94126000	Deferred        hitoolbox
PE	94126000-9417a000	Deferred        htmlrendering
PE	9417a000-9417e000	Deferred        help
PE	9417e000-94184000	Deferred        imagecapture
PE	94184000-94224000	Deferred        ink
PE	94224000-94260000	Deferred        navigationservices
PE	94260000-9427d000	Deferred        openscripting
PE	9427d000-94283000	Deferred        print
PE	94283000-94286000	Deferred        securityhi
PE	94286000-9428d000	Deferred        speechrecognition
PE	9428d000-9428e000	Deferred        cocoa
PE	9428e000-94328000	Deferred        coreaudio
PE	94328000-9433b000	Deferred        corebluetooth
PE	9433b000-94626000	Deferred        coredata
PE	9462d000-94ace000	Deferred        corefoundation
PE	94ace000-95177000	Deferred        coregraphics
PE	95177000-953ad000	Deferred        coreimage
PE	9551c000-9551d000	Deferred        coreservices
PE	9551d000-95570000	Deferred        ae
PE	95570000-95852000	Deferred        carboncore
PE	95852000-95886000	Deferred        dictionaryservices
PE	95886000-9588e000	Deferred        fsevents
PE	9588e000-959b2000	Deferred        launchservices
PE	959b2000-95a61000	Deferred        metadata
PE	95a61000-95ac2000	Deferred        osservices
PE	95ac2000-95b34000	Deferred        searchkit
PE	95b34000-95b7b000	Deferred        sharedfilelist
PE	95b7b000-95cbf000	Deferred        coretext
PE	95cbf000-95cf7000	Deferred        corevideo
PE	95cf7000-95d67000	Deferred        corewlan
PE	95d67000-95d71000	Deferred        diskarbitration
PE	95d74000-960e2000	Deferred        foundation
PE	960e2000-96113000	Deferred        gss
PE	96113000-961b6000	Deferred        iobluetooth
PE	961b6000-96252000	Deferred        iokit
PE	96252000-96259000	Deferred        iosurface
PE	962ab000-96408000	Deferred        imageio
PE	96408000-9640c000	Deferred        libgif.dylib
PE	9640c000-96505000	Deferred        libjp2.dylib
PE	96505000-96529000	Deferred        libjpeg.dylib
PE	96529000-96550000	Deferred        libpng.dylib
PE	96550000-96553000	Deferred        libradiance.dylib
PE	96553000-965aa000	Deferred        libtiff.dylib
PE	96d41000-96d5a000	Deferred        kerberos
PE	972c7000-9731a000	Deferred        metal
PE	9731a000-97323000	Deferred        netfs
PE	97323000-9732c000	Deferred        libcldcpuengine.dylib
PE	974ff000-9754c000	Deferred        opencl
PE	9754c000-97566000	Deferred        cfopendirectory
PE	97566000-97572000	Deferred        opendirectory
PE	97572000-97575000	Deferred        libcvmspluginsupport.dylib
PE	97575000-97579000	Deferred        libcorefscache.dylib
PE	97579000-9757d000	Deferred        libcorevmclient.dylib
PE	9757d000-97586000	Deferred        libgfxshared.dylib
PE	97586000-97593000	Deferred        libgl.dylib
PE	97593000-975d1000	Deferred        libglimage.dylib
PE	975d1000-97756000	Deferred        libglprogrammability.dylib
PE	97756000-9779a000	Deferred        libglu.dylib
PE	98168000-98177000	Deferred        opengl
PE	98177000-98314000	Deferred        glengine
PE	98314000-98341000	Deferred        glrendererfloat
PE	98de1000-98fe0000	Deferred        quartzcore
PE	99295000-995d1000	Deferred        security
PE	995d1000-99645000	Deferred        securityfoundation
PE	99645000-99649000	Deferred        servicemanagement
PE	99649000-996bc000	Deferred        systemconfiguration
PE	9b40c000-9b428000	Deferred        appcontainer
PE	9b428000-9b436000	Deferred        appsandbox
PE	9b436000-9b45b000	Deferred        apple80211
PE	9b45b000-9b466000	Deferred        applefscompression
PE	9b531000-9b56f000	Deferred        applejpeg
PE	9b5e8000-9b66c000	Deferred        backup
PE	9b6ab000-9b6b5000	Deferred        commonauth
PE	9ba15000-9ba27000	Deferred        coreemoji
PE	9bac4000-9baf6000	Deferred        coreservicesinternal
PE	9baf6000-9bb81000	Deferred        coresymbolication
PE	9bb81000-9bcb0000	Deferred        coreui
PE	9bcb0000-9bd41000	Deferred        coreutils
PE	9bd41000-9bda2000	Deferred        corewifi
PE	9bda2000-9bdb1000	Deferred        crashreportersupport
PE	9bdb1000-9bdbc000	Deferred        dfrfoundation
PE	9bdbc000-9be2f000	Deferred        datadetectorscore
PE	9be2f000-9be70000	Deferred        debugsymbols
PE	9be70000-9bf90000	Deferred        desktopservicespriv
PE	9c007000-9c439000	Deferred        facecore
PE	9c439000-9c43a000	Deferred        libmetal_timestamp.dylib
PE	9c43a000-9c445000	Deferred        libgpusupport.dylib
PE	9c445000-9c450000	Deferred        libgpusupportmercury.dylib
PE	9c450000-9c46c000	Deferred        generationalstorage
PE	9cae2000-9cb57000	Deferred        heimdal
PE	9ccef000-9ccf6000	Deferred        ioaccelerator
PE	9ccf6000-9cd1d000	Deferred        iconservices
PE	9cd2e000-9ceed000	Deferred        languagemodeling
PE	9ceef000-9cf18000	Deferred        multitouchsupport
PE	9cf18000-9cf23000	Deferred        netauth
PE	9cf23000-9cf61000	Deferred        performanceanalysis
PE	9cf61000-9cf7b000	Deferred        protocolbuffer
PE	9cf8b000-9cfaf000	Deferred        remoteviewservices
PE	9cfaf000-9cfb2000	Deferred        seccodewrapper
PE	9cfb2000-9cfe0000	Deferred        sharing
PE	9cfff000-9d07b000	Deferred        skylight
PE	9d07b000-9d089000	Deferred        speechrecognitioncore
PE	9d089000-9d0f1000	Deferred        symbolication
PE	9d0f1000-9d0f8000	Deferred        tcc
PE	9d0f8000-9d311000	Deferred        textureio
PE	9d311000-9d313000	Deferred        trustevaluationagent
PE	9d313000-9d486000	Deferred        uifoundation
PE	9d668000-9d726000	Deferred        viewbridge
PE	9d726000-9d72d000	Deferred        xpcservice
PE	9d72d000-9d730000	Deferred        loginsupport
PE	9e22c000-9e248000	Deferred        libcrfsuite.dylib
PE	9e248000-9e252000	Deferred        libchinesetokenizer.dylib
PE	9e252000-9e254000	Deferred        libdiagnosticmessagesclient.dyli
PE	9e254000-9e486000	Deferred        libfosl_dynamic.dylib
PE	9e486000-9e48e000	Deferred        libmatch.1.dylib
PE	9e48e000-9e48f000	Deferred        libopenscriptingutil.dylib
PE	9e48f000-9e494000	Deferred        libscreenreader.dylib
PE	9e494000-9e496000	Deferred        libsystem.b.dylib
PE	9e496000-9e4c3000	Deferred        libarchive.2.dylib
PE	9e4c3000-9e608000	Deferred        libate.dylib
PE	9e608000-9e609000	Deferred        libauto.dylib
PE	9e609000-9e61a000	Deferred        libbsm.0.dylib
PE	9e61a000-9e628000	Deferred        libbz2.1.0.dylib
PE	9e628000-9e67f000	Deferred        libc++.1.dylib
PE	9e67f000-9e6a3000	Deferred        libc++abi.dylib
PE	9e6a3000-9e6b5000	Deferred        libcmph.dylib
PE	9e6b5000-9e6c9000	Deferred        libcompression.dylib
PE	9e6c9000-9e6ca000	Deferred        libcoretls.dylib
PE	9e6ca000-9e6cc000	Deferred        libcoretls_cfhelpers.dylib
PE	9e76e000-9e85e000	Deferred        libcrypto.0.9.8.dylib
PE	9e85e000-9e8b4000	Deferred        libcups.2.dylib
PE	9e8b4000-9e8b5000	Deferred        libenergytrace.dylib
PE	9e8b6000-9e8bb000	Deferred        libheimdal-asn1.dylib
PE	9e8bb000-9e9ac000	Deferred        libiconv.2.dylib
PE	9e9ac000-9ebca000	Deferred        libicucore.a.dylib
PE	9ebca000-9ebcc000	Deferred        liblangid.dylib
PE	9ebcc000-9ebe6000	Deferred        liblzma.5.dylib
PE	9ebe6000-9ebfc000	Deferred        libmarisa.dylib
PE	9ebfc000-9eeb0000	Deferred        libmecabra.dylib
PE	9eeb0000-9ef28000	Deferred        libnetwork.dylib
PE	9ef28000-9f2ec000	Deferred        libobjc.a.dylib
PE	9f2ec000-9f2f0000	Deferred        libpam.2.dylib
PE	9f2f0000-9f31f000	Deferred        libpcap.a.dylib
PE	9f31f000-9f33c000	Deferred        libresolv.9.dylib
PE	9f33c000-9f374000	Deferred        libsandbox.1.dylib
PE	9f374000-9f4b6000	Deferred        libsqlite3.dylib
PE	9f594000-9f5a3000	Deferred        libxar.1.dylib
PE	9f5a3000-9f688000	Deferred        libxml2.2.dylib
PE	9f688000-9f6b1000	Deferred        libxslt.1.dylib
PE	9f6b1000-9f6c0000	Deferred        libz.1.dylib
PE	9f6ce000-9f6d3000	Deferred        libcache.dylib
PE	9f6d3000-9f6de000	Deferred        libcommoncrypto.dylib
PE	9f6de000-9f6e4000	Deferred        libcompiler_rt.dylib
PE	9f6e4000-9f6ed000	Deferred        libcopyfile.dylib
PE	9f6ed000-9f754000	Deferred        libcorecrypto.dylib
PE	9f754000-9f783000	Deferred        libdispatch.dylib
PE	9f783000-9f789000	Deferred        libdyld.dylib
PE	9f789000-9f78a000	Deferred        libkeymgr.dylib
PE	9f78a000-9f797000	Deferred        libkxld.dylib
PE	9f797000-9f798000	Deferred        liblaunch.dylib
PE	9f798000-9f79f000	Deferred        libmacho.dylib
PE	9f79f000-9f7a2000	Deferred        libquarantine.dylib
PE	9f7a2000-9f7a4000	Deferred        libremovefile.dylib
PE	9f7a4000-9f7bc000	Deferred        libsystem_asl.dylib
PE	9f7bc000-9f7bd000	Deferred        libsystem_blocks.dylib
PE	9f7bd000-9f84c000	Deferred        libsystem_c.dylib
PE	9f84c000-9f850000	Deferred        libsystem_configuration.dylib
PE	9f850000-9f854000	Deferred        libsystem_coreservices.dylib
PE	9f854000-9f86d000	Deferred        libsystem_coretls.dylib
PE	9f86d000-9f874000	Deferred        libsystem_dnssd.dylib
PE	9f874000-9f89c000	Deferred        libsystem_info.dylib
PE	9f89c000-9f8be000	Deferred        libsystem_kernel.dylib
PE	9f8be000-9f90b000	Deferred        libsystem_m.dylib
PE	9f90b000-9f926000	Deferred        libsystem_malloc.dylib
PE	9f926000-9f97a000	Deferred        libsystem_network.dylib
PE	9f97a000-9f984000	Deferred        libsystem_networkextension.dylib
PE	9f984000-9f98d000	Deferred        libsystem_notify.dylib
PE	9f98d000-9f994000	Deferred        libsystem_platform.dylib
PE	9f994000-9f99e000	Deferred        libsystem_pthread.dylib
PE	9f99e000-9f9a2000	Deferred        libsystem_sandbox.dylib
PE	9f9a2000-9f9a4000	Deferred        libsystem_secinit.dylib
PE	9f9a4000-9f9ac000	Deferred        libsystem_symptoms.dylib
PE	9f9ac000-9f9cd000	Deferred        libsystem_trace.dylib
PE	9f9cd000-9f9d4000	Deferred        libunwind.dylib
PE	9f9d4000-9f9fb000	Deferred        libxpc.dylib
Threads:
process  tid      prio (all id:s are in hex)
0000000c services.exe
	00000022    0
	00000021    0
	0000001a    0
	0000000e    0
	0000000d    0
00000018 winedevice.exe
	00000020    0
	0000001d    0
	0000001c    0
	00000019    0
0000001e plugplay.exe
	00000024    0
	00000023    0
	0000001f    0
0000002f explorer.exe
	00000033    0
	00000032    0
	00000031    0
	00000030    0
00000060 winewrapper.exe
	00000065    0
0000005c winewrapper.exe
	0000005b    0
00000051 sendwndcmd.exe
	0000003f    0
0000004c HWorks32.exe
	0000000f    0
00000064 winewrapper.exe
	0000005f    0
00000063 winewrapper.exe
	00000034    0
00000035 sendwndcmd.exe
	0000005d    0
00000066 (D) C:\Program Files\MattiasC\T8SuitePro\T8SuitePro.exe
	00000050    0
	0000004d    0
	00000038    0
	0000004f    0
	0000004e    0
	0000002e    2
	00000053    0
	00000055    0 <==
00000027 wineconsole.exe
	0000003a    0
System information:
    Wine build: wine-1.8-7727-g52ac2ef
    Platform: i386
    Version: Windows XP
    Host system: Darwin
    Host version: 16.4.0

**Comment by mattiasclaesson** [comment]
Reproducted the issue on a Ubuntu 17.10 with wine installed in a virtual box. Sigh,...
I think we should included a wine bottle for the suites on txsuite.

It you run t8suite.exe on the command line the following output (the above output is rather useless):

Unhandled Exception: System.ComponentModel.Win32Exception: Invalid data
 at T8SuitePro.RSACryptoServiceProviderExtension.GetDERfromPEM(String sPEM)
 at T8SuitePro.Crypto.VerifyRSASignature(String data, String expectedSignature)
 at T8SuitePro.Form1.addWizTneFilePacks()
....

**Comment by mattiasclaesson** [comment]
"Fixed it"

sudo apt-get install winetricks
winetricks dotnet40 -q crypt32
Set cryptnet.dll to native in wincfg -> libraries

It looks the built in wine implemented crypt32 is not compatible with the real thing.

**Comment by mattiasclaesson** [comment]
Link to my bottle
http://develop.trionictuning.com/TxSuiteBottle/txsuite_bottle.tar.gz
