### ISSUE TITLE
T7 search n replace issues from Myrtilos

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/TuningSuites#32]
Bonjour,

I read from T7suite release notes that the "searchreplace" function has been added to T7 SUITE, but as far as I am concerned I can't make it work : could we have a sample file ?

I need to use the "searchreplace" function with symbol name in the mask, but when I try using the same syntax as the one I use for my T8P files :
>>> searchreplace='MOVE_ROM_TO_RAM',{*E85Cal.ST_Enable},{0x00,0xF0,0x52,0xC7},{{{,},{,}}}
it doesn't do anything :(

Thanks for the help, Kind regards,
François

**Comment by mattiasclaesson** [comment]
Fixed in 1.45
