### ISSUE TITLE
Variable TCM limit in airmass viewer

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/TuningSuites#33]
[quote="Rune"]
Just a thought! Would it not be better to have the gear torque limiter @ same value as the Max torque according to myrtilos TCM limiter/mod?
Rune[/quote]
https://www.trionictuning.com/forum/viewtopic.php?f=57&t=7166&p=78891#p78891

Perhaps make a check on what torque the mod is set to?

**Comment by mattiasclaesson** [comment]
Fixed in t7 and t8 suites.
