### ISSUE TITLE
Kvaser, need to choose interface each time in T5/T7/T8suite settings before logging

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/TuningSuites#38]
Cannot connect realtime in the suites unless I first choose my interface in the suites settings and then save. Seems to find the virtual kvaser interface first?

**Comment by chriva** [comment]
Am I imagining things or isn't this also a problem in the flasher?

**Comment by MelvisR** [comment]
Flasher does not do this always. I have 2 interfaces and if I stick to the one I used last time flasher works.
Suites however does not.

**Comment by chriva** [comment]
Hmm. I only have a LapCAN but hopefully I could give it a try. The old lady has collected dust for way too long.

**Comment by mattiasclaesson** [comment]
Kvaser bugg in flasher: If adapter is inserted after program start the adapter will not find channels no matter how many times I call Canlib.canInitializeLibrary().

**Comment by mattiasclaesson** [comment]
No its not virtual inteface first. 
Problem is that the call to GetAdapterInformation() is not done until the settings dialog is shown.
Chriva solved it nicely in the flasher, maybe do the same here.

**Comment by mattiasclaesson** [comment]
Released, please test! Both T7 and T8 suites.

**Comment by mattiasclaesson** [comment]
Verified ok
