### ISSUE TITLE
Increase the 2000mg "limit" in logs

### ISSUE THREAD

**Issue by mattiasclaesson** [mattiasclaesson/TuningSuites#40]
Hi All,

Maybe someone could shed some light on this for me please.

Live logging a car that's requesting and getting more than 2000mg/c will produce a log that will export from T7Suite into CSV and it will/does show MAIR values above 2000mg/c although MREQ won't go above 2000 even though it's mapped for more.
However, if i view that log in LogWorks then everything tops out at 2000 no matter what i try even though the exported log from T7Suite clearly shows values above 2000. I know there's a channel calibration tool but i can't get it to show the truncated values, all it does it shows the same graph but at a higher value if i recalibrate it (it doesn't change the graph to show the actual missing values), which is clearly incorrect. 

So, 2 questions:
1. Can the 2000mg/c request limit in T7 be increased? I've tried search and found questions but no answers on that one.
2. What do i change in LogWorks for it to show all the logged values above 2000?

**Comment by mattiasclaesson** [comment]
I do think this is a hardcoded limit in t578suites.
I need to update the export to logworks file to another higher value. Do you have a better value in mind?

EDIT:

Guess its these one in rangeUpto 
case "m_Request":
case "MAF.m_AirInlet":
case "AirMassMast.m_Request":
retval = "2000";
break;

I created the CSV export similar to the DIF export so the same issue exist there.

/Mattias

**Comment by mattiasclaesson** [comment]
https://www.trionictuning.com/forum/viewtopic.php?f=17&t=7787

**Comment by MelvisR** [comment]
Hardcoded limit in T7/T8!

/mackan

Sent from a phone

**Comment by mattiasclaesson** [comment]
Its only DIF export.
