### ISSUE TITLE
Bluetooth, how about suport for that. Can it be done?

### ISSUE THREAD

**Issue by ModeenF** [mattiasclaesson/TuningSuites#6]
Is it all about programming or are there some other problem?

**Comment by mattiasclaesson** [comment]
Too slow, too high latency. Did not work. Setup BT as a serial COM and try if you want!

For WIFI adapters, we have added dedicated codet (even UI) in flasher/suites, but its not working properly yet. Maybe the same problems as with BT. I do not have that adapter myself.

**Comment by ChrisPea** [comment]
problem will be, that a virtual com port ist too slow.
it would be better to use the bt dongle viavirtual network rather than a virtual com port

**Comment by ModeenF** [comment]
I just had to search littel for it :)

Apperenly Bluetooth before 4.0 had problem with latency in general. People had problem watching movies etc.

BT-4.0 or smart should fix that, how mutch I don't know.
https://en.wikipedia.org/wiki/Bluetooth_low_energy

Latency pre BT-4.0 100 ms and with smart/4.0 6 ms (If the page are correct)

But I don't think there are any BT-4.0 OBD's right now, not here in Sweden..

**Comment by ChrisPea** [comment]
i got an elm 327 obd bt dongle, and i wouldn't have much trust in it, using it as flashwriter. for getting data it is ok.

**Comment by ModeenF** [comment]
True. I was more thinking of reading while driving sort of a dashboard.. But then again I don't have anything to test it with and I don't know what I would use it for..

Feels like I need to get me a cheep SAAB to test on :)

**Comment by jrespecki** [comment]
Look at DGtech DPA5 or the Nexus. Both OEM grade tools with bluetooth used in reflash etc. Actually supporting the DPA5 would be awesome, they have the full dev kit for free on their website.

**Comment by MelvisR** [comment]
Kvasers WiFi interface might be working already: https://www.kvaser.com/products/kvaser-blackbird-v2/
